module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_update: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  draggableviews: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  features: 0
  features_ui: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  inline_form_errors: 0
  kint: 0
  link: 0
  linkit: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_breadcrumb: 0
  menu_ui: 0
  metatag: 0
  metatag_verification: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  mimemail: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_redirect_import: 0
  portfolio_article: 0
  portfolio_basic_page: 0
  portfolio_blocks: 0
  portfolio_media: 0
  portfolio_navigation: 0
  portfolio_paragraphs: 0
  portfolio_project: 0
  portfolio_shared_field_storage: 0
  portfolio_site: 0
  portfolio_vocabulary: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  search_api: 0
  search_api_db: 0
  search_api_pantheon: 0
  search_api_solr: 0
  shortcut: 0
  simple_sitemap: 0
  smtp: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  term_condition: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
theme:
  stable: 0
  stark: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  portfolio: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
